import TriageBadge from './TriageBadge';

export default function SlipScreen({ patientData, onNewPatient, onEdit }) {
  const handlePrint = () => window.print();

  const rows = [
    { label: 'Token No.',  value: patientData?.token ? `#${String(patientData.token).padStart(3, '0')}` : '—' },
    { label: 'Name',       value: patientData?.name       || '—' },
    { label: 'Age',        value: patientData?.age        ? `${patientData.age} years` : '—' },
    { label: 'Complaint',  value: patientData?.complaint  || '—' },
    { label: 'Duration',   value: patientData?.duration   || '—' },
    { label: 'Severity',   value: patientData?.severity   || '—' },
    { label: 'Department', value: patientData?.department || '—' },
    { label: 'Priority',   value: patientData?.triage_level, isBadge: true },
    { label: 'Date / Time', value: patientData?.datetime  || new Date().toLocaleString() },
  ];

  return (
    <div className="max-w-lg mx-auto px-4 py-6 slide-up">
      <h2 className="text-lg font-semibold text-gray-900 mb-4 no-print">Patient Slip</h2>

      {/* Printable slip */}
      <div className="patient-slip bg-white rounded-2xl shadow-md overflow-hidden border border-gray-100">
        {/* Header */}
        <div className="bg-[#0f5c44] px-5 py-4 text-white">
          <div className="font-bold text-base">Patient Intake Slip</div>
          <div className="text-sm opacity-90">Smart Entry &amp; Healthcare Admission Triage</div>
          <div className="text-xs opacity-70 mt-0.5">Generated by SEHAT AI</div>
        </div>

        {/* Fields */}
        <div className="divide-y divide-gray-50">
          {rows.map(({ label, value, isBadge }) => (
            <div key={label} className="flex items-center px-5 py-3">
              <span className="text-xs text-gray-400 font-medium w-28 flex-shrink-0">{label}</span>
              {isBadge && value ? (
                <TriageBadge level={value} />
              ) : (
                <span className="text-sm text-gray-800 font-medium">{value}</span>
              )}
            </div>
          ))}
        </div>

        {/* Footer */}
        {patientData?.action && (
          <div className="bg-gray-50 border-t border-gray-100 px-5 py-3">
            <span className="text-xs text-gray-500 font-medium">Action: </span>
            <span className="text-xs text-gray-700">{patientData.action}</span>
          </div>
        )}
      </div>

      {/* Buttons */}
      <div className="action-buttons flex gap-3 mt-5 flex-wrap">
        <button
          onClick={onNewPatient}
          className="flex-1 py-3 rounded-xl border-2 border-gray-300 text-gray-600 font-semibold text-sm hover:bg-gray-50 transition"
        >
          New Patient
        </button>
        {onEdit && (
          <button
            onClick={onEdit}
            className="flex-1 py-3 rounded-xl border-2 border-[#1D9E75] text-[#1D9E75] font-semibold text-sm hover:bg-[#1D9E75]/5 transition"
          >
            Edit Details
          </button>
        )}
        <button
          onClick={handlePrint}
          className="flex-1 py-3 rounded-xl bg-[#1D9E75] text-white font-semibold text-sm hover:bg-[#18896a] transition shadow-sm active:scale-95"
        >
          Print Slip
        </button>
      </div>
    </div>
  );
}
